## Standard Augmentation for EEG Data

In [261]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from pathlib import Path 
import mne

from sklearn.model_selection import GroupKFold, cross_validate
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score
from sklearn.pipeline import make_pipeline
from sklearn.base import clone

In [262]:
np.random.seed(42)

In [264]:
def find_project_root():
    p = Path.cwd()
    for parent in [p, *p.parents]:
        if (parent / ".git").exists():
            return parent
    raise FileNotFoundError("Project root (with .git) not found")

PROJECT_ROOT = find_project_root()
RAW_DATA_DIR = PROJECT_ROOT / "data" / "raw" / "nm000114"
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed_features"
RESULTS_DIR = PROJECT_ROOT / "results"

print("PROJECT_ROOT:", PROJECT_ROOT)
print("RAW_DATA_DIR:", RAW_DATA_DIR)
print("PROCESSED_DIR:", PROCESSED_DIR)
print("RESULTS_DIR:", RESULTS_DIR)

PROJECT_ROOT: /home/srlee185/MSSE-277b-final-project-
RAW_DATA_DIR: /home/srlee185/MSSE-277b-final-project-/data/raw/nm000114
PROCESSED_DIR: /home/srlee185/MSSE-277b-final-project-/data/processed_features
RESULTS_DIR: /home/srlee185/MSSE-277b-final-project-/results

In [265]:
# Helper function to load a single EDF file and return the raw data object

def get_eeg_file(subject_id: str, condition: str):
    return RAW_DATA_DIR / subject_id / "eeg" / f"{subject_id}_task-{condition}_eeg.edf"

In [266]:
# Scan all files in the raw data directory to ensure we can access them

edf_files = sorted(RAW_DATA_DIR.glob("sub-*/*/*.edf"))

In [267]:
# Parser cell to read all EDF files and extract data and labels for modeling

def infer_label_from_subject(subject_id: str) -> int:
    """
    Infer the label (0 or 1) from the subject ID.
    returns: 
        0 for healthy controls (sub-HS*)
        1 for MDD patients (sub-MDD*)
    """
    subject_upper = subject_id.upper()
    if "HS" in subject_upper:
        return 0
    elif "MDD" in subject_upper:
        return 1 
    else: 
        raise ValueError(f"Could not infer label from subject ID: {subject_id}")
    
def parse_condition_from_filename(filepath: Path) -> str:
    """
    Parse the condition from the filename
    Returns:
        - eyesClosed
        - eyesOpen
        - P300
    """

    name = filepath.name 
    if "task-eyesClosed" in name:
        return "eyesClosed"
    elif "task-eyesOpen" in name:
        return "eyesOpen"
    elif "task-P300" in name:
        return "P300"
    else:
        raise ValueError(f"Could not parse condition from filename: {name}")

In [268]:
# metadata list to hold all parsed information 

rows = []

for filepath in edf_files:
    subject_id = filepath.parts[-3]  # e.g. subHS1
    condition = parse_condition_from_filename(filepath)
    label = infer_label_from_subject(subject_id)

    rows.append({
        "patient_id": subject_id,
        "recording_id": filepath.stem,
        "label": label,
        "condition": condition,
        "filepath": str(filepath),
    })


# Create a DataFrame from the metadata
metadata_df = pd.DataFrame(rows)
print(metadata_df.head())

  patient_id                  recording_id  label   condition  \
0    sub-HS1         sub-HS1_task-P300_eeg      0        P300
1    sub-HS1   sub-HS1_task-eyesClosed_eeg      0  eyesClosed
2    sub-HS1     sub-HS1_task-eyesOpen_eeg      0    eyesOpen
3   sub-HS10        sub-HS10_task-P300_eeg      0        P300
4   sub-HS10  sub-HS10_task-eyesClosed_eeg      0  eyesClosed

                                            filepath
0  /home/srlee185/MSSE-277b-final-project-/data/r...
1  /home/srlee185/MSSE-277b-final-project-/data/r...
2  /home/srlee185/MSSE-277b-final-project-/data/r...
3  /home/srlee185/MSSE-277b-final-project-/data/r...
4  /home/srlee185/MSSE-277b-final-project-/data/r...

In [269]:
COMMON_CHANNELS = [
'EEG Fp1-LE', 'EEG F3-LE', 'EEG C3-LE', 'EEG P3-LE', 'EEG O1-LE',
 'EEG F7-LE', 'EEG T3-LE', 'EEG T5-LE', 'EEG Fz-LE', 'EEG Fp2-LE', 
 'EEG F4-LE', 'EEG C4-LE', 'EEG P4-LE', 'EEG O2-LE', 'EEG F8-LE', 
 'EEG T4-LE', 'EEG T6-LE', 'EEG Cz-LE', 'EEG Pz-LE', 'EEG A2-A1'
]

print("Number of common channels:", len(COMMON_CHANNELS))

Number of common channels: 20

In [270]:
# Baseline augmentation
gfk = GroupKFold(n_splits=5)

pipeline_svm = Pipeline([
    ("scaler", StandardScaler()),
    ("clf", SVC(kernel="rbf",probability=True)
     )
])

# Standard Augmentation

In [271]:
def extract_band_power_from_file(filepath, COMMON_CHANNELS) -> np.ndarray:
    """
    Extract basic EEG band power features from the raw MNE objects.
    Returns a feature vector.
    """

    raw = mne.io.read_raw_edf(filepath, preload=True, verbose=False)
    data_raw = raw.copy()
    data_raw.pick(COMMON_CHANNELS)
    data = data_raw.get_data()
    sfreq = data_raw.info['sfreq']  # sampling frequency (e.g. 256 Hz)

    clean_data = data.copy()
    return clean_data, sfreq

def extract_band_power_from_array(data, sfreq):
    # Define frequency bands 
    bands = {
        "delta": (1, 4),     # deep sleep
        "theta": (4, 8),     # drowsiness
        "alpha": (8, 13),    # relaxed 
        "beta":  (13, 30)    # active thinking 
    }

    all_features = []

    # Loop through each channel (ch) and convert signal to frequency domain using Welch's method to estimate power spectral density (psd)
    for ch in data:        
        psd, freqs = mne.time_frequency.psd_array_welch(
            ch,
            sfreq=sfreq,
            fmin=1,
            fmax=30,
            verbose=False
        )

        total_power = psd.sum()
        
        band_features = [
            (
                psd[(freqs >= fmin) & (freqs <= fmax)].mean()
            / total_power                                      # normalize by total power to get relative power in each band
            if total_power > 0 else 0                          # handle case where total power is zero to avoid division by zero
            )                           
            for (fmin, fmax) in bands.values()
            ]
    
        all_features.append(band_features)

    return np.nan_to_num(np.array(all_features).flatten())

In [272]:
features = []
labels = []
groups_list = []
filepaths = []
conditions = []


for i, row in metadata_df.iterrows():
    fp = row['filepath']
    label = row['label']
    group = row['patient_id']

    data, sfreq = extract_band_power_from_file(fp, COMMON_CHANNELS)

    feat = extract_band_power_from_array(data, sfreq)

    features.append(feat)
    labels.append(label)
    groups_list.append(group)
    filepaths.append(fp)
    conditions.append(condition)

X = np.vstack(features)
y = np.array(labels)
groups = np.array(groups_list)
filepaths = np.array(filepaths)

In [273]:
# Separating by condition
all_conditions = ["P300", "eyesClosed", "eyesOpen"]
masks = {}

for _ in all_conditions:
    mask = metadata_df['condition'] == _
    masks[_] = mask

In [276]:
# Augmentation functions

# Time Augmenation
def time_masking(data, mask_size): # Data must be raw edf file data
    n_channels, n_times = data.shape
    raw_data = data.copy()
    max_start = max(1, n_times - mask_size)
    start = np.random.randint(0, max_start)

    raw_data[:, start:start+mask_size] = 0
    return raw_data

def time_mask_augment(filepaths_train, COMMON_CHANNELS, mask_size=900):
    X_aug = []

    for fp in filepaths_train:
        raw = mne.io.read_raw_edf(fp, preload=True, verbose=False)
        raw.pick(COMMON_CHANNELS)
        data = raw.get_data()
        sfreq = raw.info['sfreq']

        masked = time_masking(data.copy(), mask_size)

        feats = extract_band_power_from_array(masked, sfreq)
        X_aug.append(feats)

    return np.vstack(X_aug)


# Global augmentation funtions
def g_gaussian_noise(data, noise_level=0.01):
    copy = data.copy()
    noise = np.random.normal(0, noise_level * data.std(), data.shape)
    return copy + noise


def g_amplitude_scaling(data, scale_range=(0.9,1.1)):
    copy = data.copy()
    scale = np.random.uniform(*scale_range)
    return copy * scale

# feature-level data augmentation functions
def f_gaussian_noise(X, noise_std=0.01, random_state=42):
    """
    Add Gaussian noise to the feature matrix X.
    """
    rng = np.random.default_rng(random_state)
    noise = rng.normal(loc=0, scale=noise_std, size=X.shape)
    return X + noise

def f_amplitude_scaling(X, scale_low=0.9, scale_high=1.1, random_state=42):
    """
    Randomly scale the amplitude of the features in X.
    """
    rng = np.random.default_rng(random_state)
    scales = rng.uniform(low=scale_low, high=scale_high, size=(X.shape[0], 1))
    return X * scales

In [277]:
# Applying Amplitude Scaling and Gaussian Noise with Time Masking

augmentations = {
    # No augmentation
    "Baseline": lambda X, fp: X,

    # Time masking (raw EDF → masked → band power)
    "Time Mask": lambda X, fp: time_mask_augment(fp, COMMON_CHANNELS),

    # Global augmentations (feature-level)
    "Global Amplitude Scaling": lambda X, fp: g_amplitude_scaling(X),
    "Global Gaussian Noise": lambda X, fp: g_gaussian_noise(X),

    # Feature-level augmentations
    "Feature Amplitude Scaling": lambda X, fp: f_amplitude_scaling(X),
    "Feature Gaussian Noise": lambda X, fp: f_gaussian_noise(X),

    # Combinations
    "Global Gaussian + Time": lambda X, fp: g_gaussian_noise(
        time_mask_augment(fp, COMMON_CHANNELS)
    ),
    "Global Amplitude + Time": lambda X, fp: g_amplitude_scaling(
        time_mask_augment(fp, COMMON_CHANNELS)
    ),
    "Global Amplitude → Global Gaussian": lambda X, fp: g_gaussian_noise(
        g_amplitude_scaling(X)
    ),
    "Global Gaussian → Global Amplitude": lambda X, fp: g_amplitude_scaling(
        g_gaussian_noise(X)
    ),
    "Time → Global Amp → Global Gaussian": lambda X, fp: g_gaussian_noise(
        g_amplitude_scaling(time_mask_augment(fp, COMMON_CHANNELS))
    ),
    "Time → Global Gaussian → Global Amp": lambda X, fp: g_amplitude_scaling(
        g_gaussian_noise(time_mask_augment(fp, COMMON_CHANNELS))
    ),
}


def run_augmented_svm_valid(condition_name, X, y, groups, filepaths, augmenter=None):
    cv = GroupKFold(n_splits=5)
    pipeline = make_pipeline(StandardScaler(), SVC(probability=True, random_state=42))

    acc, f1, roc = [], [], []

    for fold, (train_idx, test_idx) in enumerate(cv.split(X, y, groups), start=1):
        X_train, X_test = X[train_idx], X[test_idx]
        y_train, y_test = y[train_idx], y[test_idx]
        fp_train = filepaths[train_idx].tolist()

        if augmenter is not None:
            X_train_aug = augmenter(X_train, fp_train)

            y_train_aug = y_train.copy()

            X_train_final = np.vstack([X_train, X_train_aug])
            y_train_final = np.concatenate([y_train, y_train_aug])
        else:
            X_train_final = X_train
            y_train_final = y_train

        model = clone(pipeline)
        model.fit(X_train_final, y_train_final)

        y_pred = model.predict(X_test)
        y_prob = model.predict_proba(X_test)[:, 1]

        acc.append(accuracy_score(y_test, y_pred))
        f1.append(f1_score(y_test, y_pred))
        roc.append(roc_auc_score(y_test, y_prob))

    return [
        condition_name,
        np.mean(acc),
        np.mean(f1),
        np.mean(roc)
    ]

results = []

for name, aug_fn in augmentations.items():
    results.append(
        run_augmented_svm_valid(name, X, y, groups, filepaths, augmenter=aug_fn)
    )


results_df = pd.DataFrame(
    results,
    columns=["Condition", "Accuracy", "F1", "ROC-AUC"]
)

results_df

                              Condition  Accuracy        F1   ROC-AUC
0                              Baseline  0.745277  0.772245  0.846307
1                             Time Mask  0.745277  0.772245  0.847550
2              Global Amplitude Scaling  0.739871  0.767386  0.846969
3                 Global Gaussian Noise  0.750682  0.777347  0.846344
4             Feature Amplitude Scaling  0.756238  0.781005  0.843355
5                Feature Gaussian Noise  0.755937  0.789506  0.843662
6                Global Gaussian + Time  0.739721  0.773638  0.845549
7               Global Amplitude + Time  0.750532  0.780299  0.847130
8    Global Amplitude → Global Gaussian  0.745127  0.775441  0.848026
9    Global Gaussian → Global Amplitude  0.750532  0.777094  0.846193
10  Time → Global Amp → Global Gaussian  0.756388  0.779935  0.844806
11  Time → Global Gaussian → Global Amp  0.745277  0.772245  0.845440

In [278]:
p300_mask = masks["P300"].values
X_p300 = X[p300_mask]
y_p300 = y[p300_mask]
groups_p300 = groups[p300_mask]

augmentations_p300 = {
    # No augmentation
    "Baseline (P300)": lambda X, fp: X,

    # Time masking (raw EDF → masked → band power)
    "Time Mask (P300)": lambda X, fp: time_mask_augment(fp, COMMON_CHANNELS),

    # Global augmentations (feature-level)
    "Global Amplitude Scaling (P300)": lambda X, fp: g_amplitude_scaling(X),
    "Global Gaussian Noise (P300)": lambda X, fp: g_gaussian_noise(X),

    # Feature-level augmentations
    "Feature Amplitude Scaling (P300)": lambda X, fp: f_amplitude_scaling(X),
    "Feature Gaussian Noise (P300)": lambda X, fp: f_gaussian_noise(X),

    # Combinations
    "Global Gaussian + Time (P300)": lambda X, fp: g_gaussian_noise(
        time_mask_augment(fp, COMMON_CHANNELS)
    ),
    "Global Amplitude + Time (P300)": lambda X, fp: g_amplitude_scaling(
        time_mask_augment(fp, COMMON_CHANNELS)
    ),
    "Global Amplitude → Global Gaussian (P300)": lambda X, fp: g_gaussian_noise(
        g_amplitude_scaling(X)
    ),
    "Global Gaussian → Global Amplitude (P300)": lambda X, fp: g_amplitude_scaling(
        g_gaussian_noise(X)
    ),
    "Time → Global Amp → Global Gaussian (P300)": lambda X, fp: g_gaussian_noise(
        g_amplitude_scaling(time_mask_augment(fp, COMMON_CHANNELS))
    ),
    "Time → Global Gaussian → Global Amp (P300)": lambda X, fp: g_amplitude_scaling(
        g_gaussian_noise(time_mask_augment(fp, COMMON_CHANNELS))
    ),
}

results_p300 = []

for name, aug_fn in augmentations_p300.items():
    results_p300.append(
        run_augmented_svm_valid(name, X_p300, y_p300, groups_p300, filepaths, augmenter=aug_fn)
    )

p300_results_df = pd.DataFrame(
    results_p300,
    columns=["Condition", "Accuracy", "F1", "ROC-AUC"]
)

p300_results_df

                                     Condition  Accuracy        F1   ROC-AUC
0                              Baseline (P300)  0.803846  0.839524  0.895079
1                             Time Mask (P300)  0.753846  0.799286  0.882222
2              Global Amplitude Scaling (P300)  0.803846  0.839524  0.895079
3                 Global Gaussian Noise (P300)  0.803846  0.839524  0.895079
4             Feature Amplitude Scaling (P300)  0.803846  0.839524  0.895079
5                Feature Gaussian Noise (P300)  0.803846  0.839524  0.906190
6                Global Gaussian + Time (P300)  0.753846  0.799286  0.876508
7               Global Amplitude + Time (P300)  0.720513  0.777563  0.883175
8    Global Amplitude → Global Gaussian (P300)  0.803846  0.839524  0.895079
9    Global Gaussian → Global Amplitude (P300)  0.803846  0.839524  0.895079
10  Time → Global Amp → Global Gaussian (P300)  0.737179  0.787857  0.882222
11  Time → Global Gaussian → Global Amp (P300)  0.720513  0.777563  0.887937

In [279]:
closed_mask = masks["eyesClosed"].values
X_closed = X[closed_mask]
y_closed = y[closed_mask]
groups_closed = groups[closed_mask]

augmentations_closed = {
    # No augmentation
    "Baseline (closed)": lambda X, fp: X,

    # Time masking (raw EDF → masked → band power)
    "Time Mask (closed)": lambda X, fp: time_mask_augment(fp, COMMON_CHANNELS),

    # Global augmentations (feature-level)
    "Global Amplitude Scaling (closed)": lambda X, fp: g_amplitude_scaling(X),
    "Global Gaussian Noise (closed)": lambda X, fp: g_gaussian_noise(X),

    # Feature-level augmentations
    "Feature Amplitude Scaling (closed)": lambda X, fp: f_amplitude_scaling(X),
    "Feature Gaussian Noise (closed)": lambda X, fp: f_gaussian_noise(X),

    # Combinations
    "Global Gaussian + Time (closed)": lambda X, fp: g_gaussian_noise(
        time_mask_augment(fp, COMMON_CHANNELS)
    ),
    "Global Amplitude + Time (closed)": lambda X, fp: g_amplitude_scaling(
        time_mask_augment(fp, COMMON_CHANNELS)
    ),
    "Global Amplitude → Global Gaussian (closed)": lambda X, fp: g_gaussian_noise(
        g_amplitude_scaling(X)
    ),
    "Global Gaussian → Global Amplitude (closed)": lambda X, fp: g_amplitude_scaling(
        g_gaussian_noise(X)
    ),
    "Time → Global Amp → Global Gaussian (closed)": lambda X, fp: g_gaussian_noise(
        g_amplitude_scaling(time_mask_augment(fp, COMMON_CHANNELS))
    ),
    "Time → Global Gaussian → Global Amp (closed)": lambda X, fp: g_amplitude_scaling(
        g_gaussian_noise(time_mask_augment(fp, COMMON_CHANNELS))
    ),
}

closed_results = []

for name, aug_fn in augmentations_closed.items():
    closed_results.append(
        run_augmented_svm_valid(name, X_closed, y_closed, groups_closed, filepaths, augmenter=aug_fn)
    )

closed_results_df = pd.DataFrame(
    closed_results,
    columns=["Condition", "Accuracy", "F1", "ROC-AUC"]
)

closed_results_df

                                       Condition  Accuracy        F1   ROC-AUC
0                              Baseline (closed)  0.846970  0.836239  0.924444
1                             Time Mask (closed)  0.742424  0.745256  0.834583
2              Global Amplitude Scaling (closed)  0.812121  0.809719  0.918730
3                 Global Gaussian Noise (closed)  0.846970  0.836239  0.924444
4             Feature Amplitude Scaling (closed)  0.812121  0.809719  0.918730
5                Feature Gaussian Noise (closed)  0.830303  0.825250  0.884921
6                Global Gaussian + Time (closed)  0.742424  0.745256  0.828869
7               Global Amplitude + Time (closed)  0.742424  0.745256  0.817758
8    Global Amplitude → Global Gaussian (closed)  0.846970  0.836239  0.918730
9    Global Gaussian → Global Amplitude (closed)  0.830303  0.822906  0.918730
10  Time → Global Amp → Global Gaussian (closed)  0.742424  0.745256  0.832202
11  Time → Global Gaussian → Global Amp (closed)  0.742424  0.745256  0.828869

In [285]:
open_mask = masks["eyesOpen"].values
X_open = X[open_mask]
y_open = y[open_mask]
groups_open  = groups[open_mask]

augmentations_open = {
    # No augmentation
    "Baseline (open)": lambda X, fp: X,

    # Time masking (raw EDF → masked → band power)
    "Time Mask (open)": lambda X, fp: time_mask_augment(fp, COMMON_CHANNELS),

    # Global augmentations (feature-level)
    "Global Amplitude Scaling (open)": lambda X, fp: g_amplitude_scaling(X),
    "Global Gaussian Noise (open)": lambda X, fp: g_gaussian_noise(X),

    # Feature-level augmentations
    "Feature Amplitude Scaling (open)": lambda X, fp: f_amplitude_scaling(X),
    "Feature Gaussian Noise (open)": lambda X, fp: f_gaussian_noise(X),

    # Combinations
    "Global Gaussian + Time (open)": lambda X, fp: g_gaussian_noise(
        time_mask_augment(fp, COMMON_CHANNELS)
    ),
    "Global Amplitude + Time (open)": lambda X, fp: g_amplitude_scaling(
        time_mask_augment(fp, COMMON_CHANNELS)
    ),
    "Global Amplitude → Global Gaussian (open)": lambda X, fp: g_gaussian_noise(
        g_amplitude_scaling(X)
    ),
    "Global Gaussian → Global Amplitude (open)": lambda X, fp: g_amplitude_scaling(
        g_gaussian_noise(X)
    ),
    "Time → Global Amp → Global Gaussian (open)": lambda X, fp: g_gaussian_noise(
        g_amplitude_scaling(time_mask_augment(fp, COMMON_CHANNELS))
    ),
    "Time → Global Gaussian → Global Amp (open)": lambda X, fp: g_amplitude_scaling(
        g_gaussian_noise(time_mask_augment(fp, COMMON_CHANNELS))
    ),
}

open_results = []

for name, aug_fn in augmentations_open.items():
    open_results.append(
        run_augmented_svm_valid(name, X_open, y_open, groups_open, filepaths, augmenter=aug_fn)
    )

open_results_df = pd.DataFrame(
    open_results,
    columns=["Condition", "Accuracy", "F1", "ROC-AUC"]
)

open_results_df

                                     Condition  Accuracy        F1   ROC-AUC
0                              Baseline (open)  0.721795  0.720317  0.766349
1                             Time Mask (open)  0.689744  0.732607  0.813016
2              Global Amplitude Scaling (open)  0.705128  0.711429  0.783016
3                 Global Gaussian Noise (open)  0.705128  0.711429  0.771905
4             Feature Amplitude Scaling (open)  0.705128  0.711429  0.772540
5                Feature Gaussian Noise (open)  0.674359  0.718237  0.799683
6                Global Gaussian + Time (open)  0.689744  0.740959  0.813016
7               Global Amplitude + Time (open)  0.706410  0.752387  0.807460
8    Global Amplitude → Global Gaussian (open)  0.705128  0.711429  0.771905
9    Global Gaussian → Global Amplitude (open)  0.705128  0.711429  0.793968
10  Time → Global Amp → Global Gaussian (open)  0.706410  0.752387  0.801905
11  Time → Global Gaussian → Global Amp (open)  0.738462  0.774286  0.818571

In [286]:
display(results_df)
display(p300_results_df)
display(closed_results_df)
display(open_results_df)

                              Condition  Accuracy        F1   ROC-AUC
0                              Baseline  0.745277  0.772245  0.846307
1                             Time Mask  0.745277  0.772245  0.847550
2              Global Amplitude Scaling  0.739871  0.767386  0.846969
3                 Global Gaussian Noise  0.750682  0.777347  0.846344
4             Feature Amplitude Scaling  0.756238  0.781005  0.843355
5                Feature Gaussian Noise  0.755937  0.789506  0.843662
6                Global Gaussian + Time  0.739721  0.773638  0.845549
7               Global Amplitude + Time  0.750532  0.780299  0.847130
8    Global Amplitude → Global Gaussian  0.745127  0.775441  0.848026
9    Global Gaussian → Global Amplitude  0.750532  0.777094  0.846193
10  Time → Global Amp → Global Gaussian  0.756388  0.779935  0.844806
11  Time → Global Gaussian → Global Amp  0.745277  0.772245  0.845440

                                     Condition  Accuracy        F1   ROC-AUC
0                              Baseline (P300)  0.803846  0.839524  0.895079
1                             Time Mask (P300)  0.753846  0.799286  0.882222
2              Global Amplitude Scaling (P300)  0.803846  0.839524  0.895079
3                 Global Gaussian Noise (P300)  0.803846  0.839524  0.895079
4             Feature Amplitude Scaling (P300)  0.803846  0.839524  0.895079
5                Feature Gaussian Noise (P300)  0.803846  0.839524  0.906190
6                Global Gaussian + Time (P300)  0.753846  0.799286  0.876508
7               Global Amplitude + Time (P300)  0.720513  0.777563  0.883175
8    Global Amplitude → Global Gaussian (P300)  0.803846  0.839524  0.895079
9    Global Gaussian → Global Amplitude (P300)  0.803846  0.839524  0.895079
10  Time → Global Amp → Global Gaussian (P300)  0.737179  0.787857  0.882222
11  Time → Global Gaussian → Global Amp (P300)  0.720513  0.777563  0.887937

                                       Condition  Accuracy        F1   ROC-AUC
0                              Baseline (closed)  0.846970  0.836239  0.924444
1                             Time Mask (closed)  0.742424  0.745256  0.834583
2              Global Amplitude Scaling (closed)  0.812121  0.809719  0.918730
3                 Global Gaussian Noise (closed)  0.846970  0.836239  0.924444
4             Feature Amplitude Scaling (closed)  0.812121  0.809719  0.918730
5                Feature Gaussian Noise (closed)  0.830303  0.825250  0.884921
6                Global Gaussian + Time (closed)  0.742424  0.745256  0.828869
7               Global Amplitude + Time (closed)  0.742424  0.745256  0.817758
8    Global Amplitude → Global Gaussian (closed)  0.846970  0.836239  0.918730
9    Global Gaussian → Global Amplitude (closed)  0.830303  0.822906  0.918730
10  Time → Global Amp → Global Gaussian (closed)  0.742424  0.745256  0.832202
11  Time → Global Gaussian → Global Amp (closed)  0.742424  0.745256  0.828869

                                     Condition  Accuracy        F1   ROC-AUC
0                              Baseline (open)  0.721795  0.720317  0.766349
1                             Time Mask (open)  0.689744  0.732607  0.813016
2              Global Amplitude Scaling (open)  0.705128  0.711429  0.783016
3                 Global Gaussian Noise (open)  0.705128  0.711429  0.771905
4             Feature Amplitude Scaling (open)  0.705128  0.711429  0.772540
5                Feature Gaussian Noise (open)  0.674359  0.718237  0.799683
6                Global Gaussian + Time (open)  0.689744  0.740959  0.813016
7               Global Amplitude + Time (open)  0.706410  0.752387  0.807460
8    Global Amplitude → Global Gaussian (open)  0.705128  0.711429  0.771905
9    Global Gaussian → Global Amplitude (open)  0.705128  0.711429  0.793968
10  Time → Global Amp → Global Gaussian (open)  0.706410  0.752387  0.801905
11  Time → Global Gaussian → Global Amp (open)  0.738462  0.774286  0.818571

## Discussion

The standard augmenation methods of masking, amplitude scaling and gaussain noise have minimal effects on the improvement of an SVM architecture on classifying EEG readings based on MDD condition. Applying a time mask of the first 900 time points (out of ~154880) slightly improves the model from a baseline by about 3% increase in accruacy. Any additional augmentation doesn't improve the model any further, indicating that time masking has the biggest influence. However, moving foward with the project, applying a mask on the other conditions has the most significant boost in model performance. Taking the data taken only from the P300 task has the best increase in model performance, indicating that rather than augmenting the actual data, how the data is recorded has a bigger influence on EEG data classification.